# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170307_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestocklevel',
            name='level',
            field=models.SmallIntegerField(verbose_name='Base quantity'),
        ),
    ]
