# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170312_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestocklevel',
            name='level',
            field=models.SmallIntegerField(verbose_name='Base quantity'),
        ),
    ]
