# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 12:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import enumfields.fields
import wallet.enums


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20160309_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'Transaction'},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='pre_balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SEK', 'Swedish Krona')], default='SEK', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='pre_balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=wallet.enums.TrxStatus),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=wallet.enums.TrxType),
        ),
    ]
