# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 18:58
from __future__ import unicode_literals

from django.db import migrations
from moneyed import Money


def populate_pre_balance(apps, schema_editor):
    Wallet = apps.get_model('wallet', 'Wallet')
    WalletTransaction = apps.get_model('wallet', 'WalletTransaction')

    wallet_objs = Wallet.objects.all()

    for wallet_obj in wallet_objs:
        trxs = WalletTransaction.objects.filter(wallet=wallet_obj)
        trxs = trxs.filter(trx_status__in=[0, 1])
        trxs = trxs.order_by('date_created')

        balance = Money(0, 'SEK')
        for trx in trxs:
            trx.pre_balance = balance
            trx.save()
            sign = 1 if trx.trx_type else -1
            balance += sign * trx.amount


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20160919_1224'),
    ]

    operations = [
        migrations.RunPython(populate_pre_balance)
    ]
