# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20170312_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='internal_reference',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='trx_type',
        ),
    ]
