# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:56
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import wallet.enums


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20170312_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactionstatus',
            name='status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=wallet.enums.TrxStatus, verbose_name='type'),
        ),
    ]
