# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0020_purchasestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
